source 'https://rubygems.org'

gem 'rails', '3.2.11'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'
gem 'json'
gem 'nokogiri', '1.5.9'
gem 'rsolr'
gem 'will_paginate', '~> 3.0'
gem 'colorbox-rails'
gem 'jquery-rails'
gem 'capistrano'
gem 'backbone-on-rails'
gem 'carrierwave'
gem 'prawn'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem "less-rails" #Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
  gem "twitter-bootstrap-rails"
  gem 'uglifier', '>= 1.0.3'
  gem 'compass-rails', '1.0.3'
  
  gem 'therubyracer', '0.10.2', :platforms => :ruby
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'execjs'
  # gem 'libv8', '<= 3.11.8.12'
end


  
  
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
